import { randomUUID } from 'crypto';
import fs from 'fs';
import path from 'path';

import { DATA_DIR } from './config.js';

export const CONTAINER_SECRET_MOUNT_PATH = '/run/secrets/nanoclaw.env';
export const CONTAINER_SECRETS_DIR = path.join(DATA_DIR, 'container-secrets');

const ENV_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;
const CONTAINER_NAME_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/;

export interface ExtractedContainerEnvironment {
  args: string[];
  env: Record<string, string>;
}

function parseEnvironmentSpec(spec: string, hostEnv: NodeJS.ProcessEnv): [string, string] | null {
  const separator = spec.indexOf('=');
  const key = separator === -1 ? spec : spec.slice(0, separator);
  if (!ENV_KEY_PATTERN.test(key)) {
    throw new Error(`Invalid container environment key: ${key}`);
  }

  if (separator === -1) {
    const value = hostEnv[key];
    return value === undefined ? null : [key, value];
  }
  return [key, spec.slice(separator + 1)];
}

/**
 * Remove Docker `-e/--env` arguments and return their values separately.
 *
 * OneCLI appends proxy settings directly to the Docker argument array, so
 * this runs after OneCLI has contributed its flags. Keeping the values out of
 * argv also keeps them out of `docker inspect`'s Config.Env.
 */
export function extractContainerEnvironmentArgs(
  inputArgs: string[],
  hostEnv: NodeJS.ProcessEnv = process.env,
): ExtractedContainerEnvironment {
  const args: string[] = [];
  const env: Record<string, string> = {};

  for (let index = 0; index < inputArgs.length; index += 1) {
    const arg = inputArgs[index];
    let spec: string | undefined;

    if (arg === '-e' || arg === '--env') {
      spec = inputArgs[index + 1];
      if (spec === undefined) {
        throw new Error(`${arg} requires an environment assignment`);
      }
      index += 1;
    } else if (arg.startsWith('--env=')) {
      spec = arg.slice('--env='.length);
    } else if (arg.startsWith('-e=')) {
      spec = arg.slice('-e='.length);
    }

    if (spec === undefined) {
      args.push(arg);
      continue;
    }

    const parsed = parseEnvironmentSpec(spec, hostEnv);
    if (parsed) {
      env[parsed[0]] = parsed[1];
    }
  }

  return { args, env };
}

function shellQuote(value: string): string {
  if (value.includes('\0')) {
    throw new Error('Container environment values cannot contain NUL bytes');
  }
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/** Serialize environment values as a sourceable Bash file without interpolation. */
export function serializeContainerSecrets(env: Record<string, string>): string {
  const lines = ['# Generated by NanoClaw. Contains secrets; do not copy or log.'];
  for (const key of Object.keys(env).sort()) {
    if (!ENV_KEY_PATTERN.test(key)) {
      throw new Error(`Invalid container environment key: ${key}`);
    }
    lines.push(`export ${key}=${shellQuote(env[key])}`);
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Write one container's environment bundle with owner-only permissions.
 * Returns null when no values need forwarding.
 */
export function writeContainerSecretFile(
  containerName: string,
  env: Record<string, string>,
  directory = CONTAINER_SECRETS_DIR,
): string | null {
  if (Object.keys(env).length === 0) return null;
  if (!CONTAINER_NAME_PATTERN.test(containerName)) {
    throw new Error(`Invalid container name: ${containerName}`);
  }

  fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
  fs.chmodSync(directory, 0o700);

  const uniqueId = randomUUID();
  const finalPath = path.join(directory, `${containerName}.${uniqueId}.env`);
  const temporaryPath = path.join(directory, `.${containerName}.${process.pid}.${uniqueId}.tmp`);

  try {
    fs.writeFileSync(temporaryPath, serializeContainerSecrets(env), {
      encoding: 'utf8',
      flag: 'wx',
      mode: 0o600,
    });
    fs.chmodSync(temporaryPath, 0o600);

    // NanoClaw normally maps the host UID into the container. If the host
    // service is running as root, the image still runs as the `node` user
    // (UID/GID 1000), so hand ownership to that user before bind-mounting.
    if (process.getuid?.() === 0) {
      fs.chownSync(temporaryPath, 1000, 1000);
    }

    fs.renameSync(temporaryPath, finalPath);
    return finalPath;
  } catch (error) {
    fs.rmSync(temporaryPath, { force: true });
    throw error;
  }
}

export function removeContainerSecretFile(filePath: string | null | undefined): void {
  if (!filePath) return;
  fs.rmSync(filePath, { force: true });
}

/** Remove bundles left by a host crash, after this install's orphans stop. */
export function cleanupContainerSecretFiles(directory = CONTAINER_SECRETS_DIR): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(directory, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
    throw error;
  }

  for (const entry of entries) {
    fs.rmSync(path.join(directory, entry.name), {
      force: true,
      recursive: entry.isDirectory(),
    });
  }
}
